apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "excalidraw.fullname" . }}
  labels:
    app: {{ include "excalidraw.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "excalidraw.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "excalidraw.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: excalidraw/excalidraw@sha256:20ffa04668e19616bb0c1b3632849e5cd96e0bc7a1336b73d9d072667f2c2854
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          resources:
{{ toYaml .Values.resources | indent 12 }}
